collision_alpha: 0.1
collision_size: 1.0
collision_zone_alpha: 0.075
collision_zone_base_diameter: 0.025
color_scheme:
  aio_jackal: tab:pink
  aio_rto: tab:pink
  aio_turtlebot3_burger: tab:pink
  aio_youbot: tab:pink
  arena_turtlebot3_burger: tab:grey
  cadrl_jackal: tab:olive
  cadrl_rto: tab:olive
  cadrl_turtlebot3_burger: tab:olive
  cadrl_youbot: tab:olive
  dwa_jackal: tab:red
  dwa_rto: tab:red
  dwa_turtlebot3_burger: tab:red
  dwa_turtlebot3_burger_3d: tab:red
  dwa_turtlebot3_burger_real: tab:red
  dwa_youbot: tab:red
  guldenring_jackal: tab:brown
  guldenring_turtlebot3_burger: tab:brown
  mpc_jackal: tab:green
  mpc_rto: tab:green
  mpc_turtlebot3_burger: tab:green
  mpc_youbot: tab:green
  navrep_jackal: tab:purple
  navrep_rto: tab:purple
  navrep_turtlebot3_burger: tab:purple
  navrep_youbot: tab:purple
  rosnav_jackal: tab:blue
  rosnav_rto: tab:blue
  rosnav_turtlebot3_burger: tab:blue
  rosnav_turtlebot3_burger_3d: tab:blue
  rosnav_turtlebot3_burger_real: tab:blue
  rosnav_youbot: tab:blue
  teb_jackal: tab:orange
  teb_rto: tab:orange
  teb_turtlebot3_burger: tab:orange
  teb_turtlebot3_burger_3d: tab:green
  teb_turtlebot3_burger_real: tab:green
  teb_youbot: tab:orange
goal_marker: o
goal_point_color: tab:green
goal_size: 12
labels:
  aio_jackal: AIO
  aio_rto: AIO
  aio_turtlebot3_burger: AIO
  aio_youbot: AIO
  arena_turtlebot3_burger: ARENA
  cadrl_jackal: CADRL
  cadrl_rto: CADRL
  cadrl_turtlebot3_burger: CADRL
  cadrl_youbot: CADRL
  dwa_jackal: DWA
  dwa_rto: DWA
  dwa_turtlebot3_burger: DWA
  dwa_turtlebot3_burger_3d: DWA_3D
  dwa_turtlebot3_burger_real: DWA_R
  dwa_youbot: DWA
  guldenring_jackal: GRING
  guldenring_turtlebot3_burger: GRING
  mpc_jackal: MPC
  mpc_rto: MPC
  mpc_turtlebot3_burger: MPC
  mpc_youbot: MPC
  navrep_jackal: NAVREP
  navrep_rto: NAVREP
  navrep_turtlebot3_burger: NAVREP
  navrep_youbot: NAVREP
  rosnav_jackal: ROSNAV
  rosnav_rto: ROSNAV
  rosnav_turtlebot3_burger: ROSNAV
  rosnav_turtlebot3_burger_3d: ROSNAV_3D
  rosnav_turtlebot3_burger_real: ROSNAV_R
  rosnav_youbot: ROSNAV
  teb_jackal: TEB
  teb_rto: TEB
  teb_turtlebot3_burger: TEB
  teb_turtlebot3_burger_3d: TEB_3D
  teb_turtlebot3_burger_real: TEB_R
  teb_youbot: TEB
latex: false
leave_out_metric:
- cusps
leave_out_planner:
- ''
most_recent_file: data_22-02-22_23-26-55_scenario01.json
obstacle_color: black
obstacle_radius: 0.3
path_3D_alpha: 0.6
path_alpha: 1.0
path_arrow_color: black
path_arrow_size: 3
path_size: 0.05
plot_barplot_alpha: 1.0
plot_barplot_capsize: 0.4
plot_barplot_errorbars: false
plot_barplot_errorcolor: black
plot_barplot_width: 0.5
plot_collision_zones: true
plot_collisions: true
plot_obs_in_one: true
plot_obs_in_one_alpha: 1.0
plot_obs_in_one_axes_tick_size: 16
plot_obs_in_one_capsize: 0.05
plot_obs_in_one_errorbars: false
plot_obs_in_one_errorcolor: black
plot_progression: false
plot_progression_size: 3
plot_progression_steps: 20
plot_qualitative: true
plot_qualitative_axes: true
plot_qualitative_axes_size: 16
plot_qualitative_axes_ticks_size: 16
plot_qualitative_legend: false
plot_qualitative_legend_fontsize: 10
plot_qualitative_legend_location: lower right
plot_qualitative_title: true
plot_qualitative_title_size: 18
plot_quantitative: true
plot_quantitative_axes_label_size: 16
plot_quantitative_axes_tick_size: 18
plot_quantitative_labels:
  angle_over_length: ''
  collision: ''
  computation_time: ''
  cusps: ''
  jerk: ''
  max_clearing_distance: ''
  max_curvature: ''
  mean_clearing_distance: ''
  median_clearing_distance: ''
  min_clearing_distance: ''
  normalized_curvature: ''
  obstacle_number: ''
  path_length: ''
  planner: ''
  roughness: ''
  success: ''
  time: ''
plot_quantitative_legend: false
plot_quantitative_legend_fontsize: 12
plot_quantitative_legend_location: upper left
plot_quantitative_suptitle: false
plot_quantitative_suptitle_size: 18
plot_quantitative_title: false
plot_quantitative_title_size: 16
plot_quantitative_violin: false
plot_quantitative_violin_inner: point
plot_quantitative_ygrid: true
plot_success_alpha: 1.0
plot_success_collision_color: tab:red
plot_success_success_color: tab:green
plot_success_time_out_color: tab:blue
plot_success_width: 0.5
specified_data_filename: ''
specify_data: false
start_marker: '*'
start_point_color: goldenrod
start_size: 12
