mobile_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'wheel_left_joint'
  right_wheel : 'wheel_right_joint'
  publish_rate: 50.0
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Velocity commands timeout [s]
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_footprint

  # Preserve turning radius when limiting speed/acceleration/jerk
  preserve_turning_radius: true

  # Publish actual velocity cmd
  publish_cmd: true

  # Publish tf odom?
  enable_odom_tf: true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           :  1.0 # m/s
      min_velocity           : -0.2 # m/s
      has_acceleration_limits: true
      max_acceleration       :  1.0 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : !degrees 120.0
      has_acceleration_limits: true
      max_acceleration       : !degrees 120.0
